// generated by unplugin-svelte-components
// We suggest you to commit this file into source control
declare global {
    const GBtn: typeof import("./src/PACKAGE/components/GBtn.svelte")["default"]
    const GCheckbox: typeof import("./src/PACKAGE/components/GCheckbox.svelte")["default"]
    const GCheckboxGroup: typeof import("./src/PACKAGE/components/GCheckboxGroup.svelte")["default"]
    const GDebug: typeof import("./src/PACKAGE/components/GDebug.svelte")["default"]
    const GDevNote: typeof import("./src/PACKAGE/components/GDevNote.svelte")["default"]
    const GIcon: typeof import("./src/PACKAGE/components/GIcon.svelte")["default"]
    const GIconBtn: typeof import("./src/PACKAGE/components/GIconBtn.svelte")["default"]
    const GRadioGroup: typeof import("./src/PACKAGE/components/GRadioGroup.svelte")["default"]
    const GSegmentedControl: typeof import("./src/PACKAGE/components/GSegmentedControl.svelte")["default"]
    const GSortableCards: typeof import("./src/PACKAGE/components/GSortableCards.svelte")["default"]
    const GTextInput: typeof import("./src/PACKAGE/components/GTextInput.svelte")["default"]
}

export {}
