import {
  mdiArrowDown,
  mdiArrowLeft,
  mdiArrowRight,
  mdiArrowULeftTop,
  mdiArrowUp,
  mdiArrowURightTop,
  mdiBook,
  mdiChartLine,
  mdiCheck,
  mdiChevronDown,
  mdiChevronLeft,
  mdiChevronRight,
  mdiChevronUp,
  mdiClose,
  mdiCodeJson,
  mdiContentCopy,
  mdiDelete,
  mdiDragVertical,
  mdiFormatBold,
  mdiFormatItalic,
  mdiFormatListBulleted,
  mdiFormatListNumbered,
  mdiFormatQuoteClose,
  mdiFormatStrikethroughVariant,
  mdiFormatUnderline,
  mdiHammerScrewdriver,
  mdiHome,
  mdiLink,
  mdiLinkOff,
  mdiMagnify,
  mdiMarker,
  mdiMenu,
  mdiMinus,
  mdiPencil,
  mdiPlus,
  mdiPoll,
  mdiTable,
  mdiViewList,
  mdiXml,
} from '@mdi/js';

import {
  darkMode,
  firebase,
  gitHub,
  lightMode,
  nbMedia,
  systemMode,
} from './custom-icon-paths';

const icons = {
  arrowDown: mdiArrowDown,
  arrowLeft: mdiArrowLeft,
  arrowRight: mdiArrowRight,
  arrowUp: mdiArrowUp,
  book: mdiBook,
  chartLine: mdiChartLine,
  check: mdiCheck,
  chevronDown: mdiChevronDown,
  chevronLeft: mdiChevronLeft,
  chevronRight: mdiChevronRight,
  chevronUp: mdiChevronUp,
  close: mdiClose,
  code: mdiXml,
  copy: mdiContentCopy,
  darkMode,
  delete: mdiDelete,
  dragVertical: mdiDragVertical,
  edit: mdiPencil,
  firebase,
  formatBlockquote: mdiFormatQuoteClose,
  formatBold: mdiFormatBold,
  formatHighlight: mdiMarker,
  formatItalic: mdiFormatItalic,
  formatListBulleted: mdiFormatListBulleted,
  formatListNumbered: mdiFormatListNumbered,
  formatStrikethrough: mdiFormatStrikethroughVariant,
  formatUnderline: mdiFormatUnderline,
  gitHub,
  home: mdiHome,
  json: mdiCodeJson,
  lightMode,
  link: mdiLink,
  linkOff: mdiLinkOff,
  menu: mdiMenu,
  minus: mdiMinus,
  nbMedia,
  pencil: mdiPencil,
  plus: mdiPlus,
  poll: mdiPoll,
  redo: mdiArrowURightTop,
  search: mdiMagnify,
  systemMode,
  table: mdiTable,
  tools: mdiHammerScrewdriver,
  undo: mdiArrowULeftTop,
  viewList: mdiViewList,
};

export default icons;
export type IconName = keyof typeof icons;
